[13.0][fix] base_tier_validation
OCA/server-ux pull request #117
Opened 2019-12-13 13:19 UTC by LoisRForgeFlow

Forward port of https://github.com/OCA/server-ux/pull/112.

cc @ps-tubtim

2019-12-17 13:04 UTC, HviorForgeFlow requested changes

2019-12-17 13:04 UTC, HviorForgeFlow commented on base_tier_validation/tests/test_tier_validation.py
> +        self.assertEqual(comment, "A review was rejected by John. (Test Comment)")
r/sudo/with_user

2019-12-18 11:14 UTC, LoisRForgeFlow commented on base_tier_validation/tests/test_tier_validation.py
> +        self.assertEqual(comment, "A review was rejected by John. (Test Comment)")
done!

2019-12-18 11:41 UTC, HviorForgeFlow approved these changes
:+1:

2019-12-19 09:06 UTC, AdriaGForgeFlow approved these changes
Code review :+1:

2019-12-19 09:09 UTC, ps-tubtim approved these changes

2019-12-30 08:51 UTC, etobella approved these changes

2020-01-08 15:33 UTC, JordiBForgeFlow commented
/ocabot merge

2020-01-08 15:49 UTC, merged