[ADD] sequence_reset_period [WIP]
OCA/server-ux pull request #16
Opened 2018-05-18 13:05 UTC by etobella

This module allows to configure when the period related sequences generates the new periods.

Initially, odoo generates them yearly, but sometimes it could be usefult to configure them daily or monthly.

2018-05-18 14:14 UTC, JordiBForgeFlow requested changes
See my comments

2018-05-18 14:14 UTC, JordiBForgeFlow commented on sequence_reset_period/__init__.py
> +# License LGPL-3.0 or later (http://www.gnu.org/licenses/lgpl.html).
Not needed in init files.

2018-05-18 14:14 UTC, JordiBForgeFlow commented on sequence_reset_period/models/ir_sequence.py
> +    range_reset = fields.Selection([
default to yearly?

2018-05-18 14:14 UTC, JordiBForgeFlow commented on sequence_reset_period/models/ir_sequence.py
> +    def _create_date_range_seq(self, date):
ensure_one()

2018-05-18 14:14 UTC, JordiBForgeFlow commented on sequence_reset_period/models/ir_sequence.py
> +    def _compute_date_from_to(self, date):
ensure_one()

2018-05-18 14:14 UTC, jbeficent commented on sequence_reset_period/models/ir_sequence.py
> +    def _compute_date_from_to(self, date):
Perhaps you should consider, setting by default (pseudo code):
from dateutil.relativedelta import relativedelta
dt = datetime.strptime(day, '%d/%b/%Y')
if yearly:
start = date(dt.today().year, 1, 1)
end = date(dt.today().year, 12, 31)
elif 'weekly':
start = dt - timedelta(days=dt.weekday())
end = start + timedelta(days=6)
elif 'monthly':
start = dt + relativedelta(day=1)
end = dt + relativedelta(day=1, months=+1, days=-1)

2018-05-22 09:40 UTC, etobella commented on sequence_reset_period/models/ir_sequence.py
> +    range_reset = fields.Selection([
I don't think so, because it shouldn't be set if `use_date_range` is False

2018-05-22 14:45 UTC, JordiBForgeFlow approved these changes

2018-05-22 14:46 UTC, JordiBForgeFlow commented
:+1: Functional and technical review. Works like a charm!

2018-05-23 07:37 UTC, HviorForgeFlow approved these changes
LGTM :+1: Functional and code review

2018-05-23 07:37 UTC, hveficent commented on sequence_reset_period/README.rst
> +.. image:: https://img.shields.io/badge/licence-LGPL--3-blue.svg
Better to use .png format

2018-06-11 10:17 UTC, merged