[ADD][11.0] Add base_filter_hidden module
OCA/server-ux pull request #27
Opened 2018-10-02 14:17 UTC by acsonefho

- [x] New module "base_filter_hidden";
- [x] Add new field "is_system" into ir.filters (these filters are not loaded into web-interface (views));
- [x] Unit test added;

Any better ideas/improvements are welcome

2018-10-03 10:15 UTC, sebalix commented
A related module for Odoo 8 by @hbrunn : https://github.com/OCA/server-tools/tree/8.0/base_ir_filters_active
Are they complementary or yours is a better implementation?

2018-10-08 08:27 UTC, acsonefho commented
@sebalix Thank you for your comment.
The MR in v8.0 is not the same (and the added `active` field already exists in v11.0).
The goal of this MR is to hide some "technical" `ir.filters` without inactive them, because we'll use it. We just don't need to display them into the search view.

2018-10-08 12:16 UTC, sebalix approved these changes

2018-10-11 09:05 UTC, lmignon approved these changes
Great usability improvement when you use filters for some internal business processes as in https://github.com/OCA/product-attribute/pull/376/files

2019-02-20 18:40 UTC, NL66278 commented on base_filter_hidden/__manifest__.py
> +    'description': """
Description key is deprecated, please remove.

2019-02-20 18:40 UTC, NL66278 commented on base_filter_hidden/__manifest__.py
> +# Copyright 2018 ACSONE SA/NV (<http://acsone.eu>)
Use https: for copyright and licence lines.

2019-02-20 18:51 UTC, NL66278 requested changes
I agree the module might be very usefull, but I think it can also be more simple and efficient.

As it is the module reads all the normal filters, then does work to remove the system filters.

It would be more efficient to call super in the get_filters method with some context key that system filters are not wanted. Then override the search method to add a criterium to the domain, if the context key is set, to not select system filters.

2019-04-01 10:08 UTC, bealdav commented
I think @NL66278 remark could be added to roadmap and merge as it : tests and approved.

2021-11-28 12:14 UTC, closed without merging