[12.0][MIG] mass_editing: Migration to 12.0
OCA/server-ux pull request #29
Opened 2018-10-08 10:32 UTC by aitorbouzas

Migration to 12.0

2018-10-08 11:35 UTC, aitorbouzas commented
I'll throw two questions:

1. Why isn't travis running?
2. When I run my tests locally [this line](https://github.com/OCA/server-ux/pull/29/files#diff-b0d63fd5b8ada4cfacc32861676faea3R263) fails because the uninstall hook cannot find the register in database (looks like there's not in there, is it because it is a transaction and it is not commited?)

2018-10-08 13:51 UTC, aitorbouzas commented
Just fixed point 2 by deleting the actions with the env instead of a direct SQL execution with cr.

2018-10-10 13:51 UTC, aitorbouzas commented
@pedrobaeza this is ready, but i'm getting lint errors with module date_range. What should I do?

2018-10-11 13:04 UTC, aitorbouzas commented
Green and ready. @SerpentCS can you review?

2018-10-18 20:16 UTC, hugho-ad commented on mass_editing/README.rst
> +   :target: https://runbot.odoo-community.org/runbot/250/11.0
`s/11.0/12.0/g`

2018-10-18 21:45 UTC, hugho-ad approved these changes

2018-10-19 07:25 UTC, simahawk requested changes

2018-10-19 07:25 UTC, simahawk commented on mass_editing/__manifest__.py
> +    'website': 'http://www.serpentcs.com',
https://github.com/OCA/server-ux

2018-10-19 07:25 UTC, simahawk commented on mass_editing/__manifest__.py
> +    'installable': True,
all these flags are defaults, you can drop them

2018-10-19 07:25 UTC, simahawk commented on mass_editing/models/ir_model_fields.py
> +                                  list(map(int, domain[2][1:-1].split(','))))]
`[int(x) for x in domain[2][1:-1].split(',')]`

2018-10-19 07:25 UTC, simahawk commented on mass_editing/readme/USAGE.rst
> +   :alt: Try me on Runbot
remove this, it comes w/ README generator

2018-10-19 07:25 UTC, simahawk commented on mass_editing/tests/test_mass_editing.py
> +class TestMassEditing(common.TransactionCase):
please boost test suite by using:
1. SavepointCase
2. setUp -> setUpClass
3. disable tracking `cls.env = cls.env(context=dict(cls.env.context, tracking_disable=True))`

2018-10-19 07:25 UTC, simahawk commented on mass_editing/views/mass_editing_view.xml
> +                        <group>
name inner groups at least?

2018-10-19 07:25 UTC, simahawk commented on mass_editing/wizard/mass_editing_wizard.py
> +        context = self._context
self.env.context

2018-10-19 07:25 UTC, simahawk commented on mass_editing/wizard/mass_editing_wizard.py
> +            super(MassEditingWizard, self).fields_view_get(view_id=view_id,
super()

2018-10-19 07:25 UTC, simahawk commented on mass_editing/wizard/mass_editing_wizard.py
> +        if (self._context.get('active_model') and
self.env.context

2018-10-19 10:14 UTC, aitorbouzas commented on mass_editing/models/ir_model_fields.py
> +                                  list(map(int, domain[2][1:-1].split(','))))]
```suggestion
                                  [int(x) for x in domain[2][1:-1].split(',')]
```
Testing the new thingy

2018-10-31 18:21 UTC, hugho-ad commented
I'll continue this, I'm interested to have this module migrated
https://github.com/OCA/server-ux/pull/41

2018-10-31 21:00 UTC, closed without merging