[14.0] [mig] multi_step_wizard
OCA/server-ux pull request #303
Opened 2021-03-04 06:18 UTC by schhatbar

2021-03-04 08:33 UTC, dsolanki-initos approved these changes
LGTM

2021-03-05 08:47 UTC, schhatbar commented
@tarteo Can you please review this PR ?

2021-03-12 05:21 UTC, schhatbar commented
@LoisRForgeFlow Can you please review this PR?
Thanks in Advance!

2021-03-17 05:11 UTC, schhatbar-initos commented
@TDu Can you please review this PR?
Thanks in Advance!

2021-03-23 13:01 UTC, schhatbar-initos commented
@etobella Can you please review this PR?
Thanks in Advance!

2021-03-23 15:01 UTC, etobella requested changes
I know that this was not done by you, but I think now is a good moment to fix it. WDYT?

2021-03-23 15:01 UTC, etobella commented on multi_step_wizard/__init__.py
> +from .tests import multi_step_wizard_test
Is not a good idea to load this model, please, use odoo_test_helper as it is done in
https://github.com/OCA/server-ux/blob/14.0/base_tier_validation/tests/common.py#L9
this way we can avoid this model in the installation.

2021-03-31 05:21 UTC, schhatbar-initos commented
@etobella I've made the changes as suggested. Can you please check is it fine enough with using odoo_test_helper?

2021-03-31 07:14 UTC, simahawk approved these changes
pre-approving

2021-03-31 07:14 UTC, simahawk commented on multi_step_wizard/tests/test_multi_step_wizard.py
> +class CommonTierValidation(common.SavepointCase):
`TestMultiStepWizard` and replace all calls to super w/ `super()`, no need for the class name.

2021-04-02 05:20 UTC, dsolanki-initos approved these changes

2021-04-02 05:21 UTC, schhatbar-initos commented
@simahawk Can you re-review this PR?
Thanks in Advance!

2021-04-02 06:32 UTC, simahawk commented
@etobella fine for you?

2021-04-02 07:15 UTC, etobella approved these changes

2021-04-02 07:17 UTC, schhatbar-initos commented
@simahawk Can you merge this PR hence it is approved?
Thanks in Advance!

2021-04-02 07:56 UTC, simahawk commented
/ocabot merge nobump

2021-04-02 08:07 UTC, merged