[13.0][IMP] mass_editing: improvement to apply update
OCA/server-ux pull request #348
Opened 2021-05-26 07:20 UTC by acsonefho

**Improvements:**
- mass_operation_abstract: let the possibility to use the `active_domain` (instead of always `active_ids`);
- mass_edition unit test: disable tracking (minor improvement);
- mass_edition code: split the update of target recordset into a new function to have an inherit point;
- mass_edition code: split the create to avoid mix values of the wizard and values of target records.

**Why using active_domain?**
In some case, when you select all items (the dedicated select-box item), Odoo fill `active_ids` with only the 80 items displayed into the tree view (even if you have thousands of records). And sometimes it's not possible to display all of them because there is too much records.

2021-05-26 09:19 UTC, Cedric-Pigeon approved these changes

2021-05-31 07:33 UTC, StefanRijnhart commented on mass_editing/wizard/mass_editing_wizard.py
> +    use_active_domain = fields.Boolean(
This is the technical term, which might not make a lot of sense to the users. Maybe you could reword using something like 'search results'?

2021-05-31 07:37 UTC, StefanRijnhart commented
A test for the active domain functionality would be good, and would probably make codecov happy as well.

2021-08-04 11:29 UTC, simahawk requested changes
can you check @StefanRijnhart comment as well?

2021-08-04 11:29 UTC, simahawk commented on mass_editing/tests/test_mass_editing.py
>      def setUp(self):
as you are here... can you move it to SavepointCase and do this in setUpClass?

2021-08-05 08:23 UTC, simahawk approved these changes

2021-08-05 08:24 UTC, simahawk commented
/ocabot merge minor

will you port it to v14?

2021-08-05 08:27 UTC, simahawk commented
> /ocabot merge minor
> 
> will you port it to v14?

nevermind, I linked this to v14 mig https://github.com/OCA/server-ux/pull/298 -> can you review it?

2021-08-05 08:36 UTC, dzungtran89 commented
ok @simahawk , I'll port the update to v14

2021-08-05 09:00 UTC, merged