[MIG] 15.0 mass_editing
OCA/server-ux pull request #409
Opened 2021-11-22 16:01 UTC by Tatider

2021-11-27 17:19 UTC, dreispt approved these changes

2021-12-13 07:52 UTC, LoisRForgeFlow commented
/ocabot migration mass_editing

2021-12-13 09:42 UTC, JasminSForgeFlow approved these changes
LGTM!

2021-12-14 14:22 UTC, legalsylvain commented
/ocabot rebase

2021-12-14 14:24 UTC, legalsylvain commented
Hi @Tatider : could you rebase, I'd like to test on runboat, but the buid is not available.

thanks

2021-12-17 15:21 UTC, Tatider commented
@legalsylvain rebased

2021-12-18 09:51 UTC, HaraldPanten requested changes
It's functionally working fine, but you have to correct the commit message. You wrote that this is the migration for V14, but you're migrating the module to V15.

**See my screenshot:**


<img width="426" alt="Captura de pantalla 2021-12-18 a las 10 48 18" src="https://user-images.githubusercontent.com/32449357/146636847-e724905b-c03c-446d-9c04-94a1eb12c523.png">

2021-12-20 08:16 UTC, Tatider commented
@HaraldPanten Oh. my bad. The commit message is fixed now.

2021-12-20 08:21 UTC, HaraldPanten commented
I still see Migration to 14.0. Didn't you force the push?

2021-12-21 15:37 UTC, Tatider commented
@HaraldPanten now should be better (I hadn't noticed it asked for key phase)

2021-12-21 17:43 UTC, HaraldPanten approved these changes
LGTM

2021-12-28 08:30 UTC, jcdrubay commented
Looking forward to the merge :)

2021-12-28 09:15 UTC, simahawk commented
/ocabot merge nobump

2021-12-28 09:20 UTC, merged