[15.0][MIG] mig date_range
OCA/server-ux pull request #414
Opened 2021-11-29 11:12 UTC by JoanMForgeFlow

Supersede https://github.com/OCA/server-ux/pull/401

2021-12-07 12:58 UTC, HaraldPanten commented
@pedrobaeza could you approve workflows here? THX.

2021-12-09 17:20 UTC, HaraldPanten commented
@JoanMForgeFlow could you check pre-commit?

2021-12-10 08:00 UTC, JoanMForgeFlow commented
> @JoanMForgeFlow could you check pre-commit?

done!

2021-12-10 08:12 UTC, HaraldPanten approved these changes
Functional review 👍 

@ValentinVinagre @pedrobaeza

2021-12-10 08:51 UTC, ValentinVinagre commented on date_range/__manifest__.py
> +    "version": "15.0.1.0.1",
Change to 15.0.1.0.0

2021-12-10 11:09 UTC, JoanMForgeFlow commented on date_range/__manifest__.py
> +    "version": "15.0.1.0.1",
done!

2021-12-10 11:55 UTC, ValentinVinagre approved these changes

2021-12-10 11:56 UTC, HaraldPanten commented
@pedrobaeza do you mind merging this one in order to continue with the migration of --> https://github.com/OCA/account-financial-reporting/pull/837 ?

THX!

2021-12-10 12:45 UTC, AaronHForgeFlow reviewed
Seems to work ok. Can you include the improvements of https://github.com/OCA/server-ux/pull/413 ?

2021-12-11 16:51 UTC, pedrobaeza requested changes
Missing changes from #413

2021-12-11 16:52 UTC, pedrobaeza commented
/ocabot migration date_range

2021-12-15 08:20 UTC, HaraldPanten commented
@JoanMForgeFlow @AaronHForgeFlow could you continue with the migration, please? We need to keep working in other modules depending on this one. 🙏

THX!

2021-12-15 08:46 UTC, JoanMForgeFlow commented
> @JoanMForgeFlow @AaronHForgeFlow could you continue with the migration, please? We need to keep working in other modules depending on this one. pray
> 
> THX!

yes!

2021-12-15 11:53 UTC, JoanMForgeFlow commented
> Missing changes from #413

@pedrobaeza I am trying to import the odoo_test_helper library, in the test-requirements.txt file, and it gives me the following error. Any idea how to fix it
![Captura de pantalla de 2021-12-15 12-34-32](https://user-images.githubusercontent.com/90242955/146181893-ca3db490-24ac-4c8e-a198-c15ce8720485.png)
?

2021-12-15 11:57 UTC, sbidoul commented
@JoanMForgeFlow just add `odoo-test-helper` in a `test-requirements.txt` file at the repo root.

2021-12-15 12:22 UTC, JoanMForgeFlow commented
> @JoanMForgeFlow just add `odoo-test-helper` in a `test-requirements.txt` file at the repo root.

@sbidoul I had already tried it  and it doesn't work, that's why I was asking.

2021-12-15 12:30 UTC, sbidoul commented
@JoanMForgeFlow it should work. Please retry and we'll look at the exact log/error.

2021-12-16 09:58 UTC, JoanMForgeFlow commented
> @JoanMForgeFlow it should work. Please retry and we'll look at the exact log/error.

It worked!

2021-12-16 10:01 UTC, JoanMForgeFlow commented
> Missing changes from #413

@pedrobaeza @AaronHForgeFlow I have already joined the pending PRs, but now I am going to solve the last commit since I have accidentally joined it with the pre-commit.

2021-12-16 12:44 UTC, JoanMForgeFlow commented
@sbidoul When github installs the dependencies, it installs the library: odoo-test-helper-1.1.0, but I think it is out of date, how could I specify in the test-requirements.txt file, the latest version of the OCA repository: https://github.com/OCA/odoo-test-helper.

Another question, from where does CI downloads the dependencies written in the test-requirements.txt file.

2021-12-16 13:11 UTC, sbidoul commented
> @sbidoul When github installs the dependencies, it installs the library: odoo-test-helper-1.1.0, but I think it is out of date, how could I specify in the test-requirements.txt file, the latest version of the OCA repository: https://github.com/OCA/odoo-test-helper.

You can use the usual git reference syntax: `odoo-test-helper @ git+https://github.com/OCA/odoo-test-helper@master`
I think @simahawk was going to setup an release process for odoo-test-helper.

> Another question, from where does CI downloads the dependencies written in the test-requirements.txt file.

The short answer is: from PyPI.org. A longest answer is it comes from an OCA-hosted index that redirects to PyPI but filters out non-oca Odoo addons, to make sure we test only with OCA dependencies. The [default index is defined in the oca/oca-ci image](https://github.com/OCA/oca-ci/blob/c24a51d3f09c81bfdfa737de9ed16f70ef0a0d7d/Dockerfile#L146-L148).

2021-12-16 13:28 UTC, simahawk commented
>You can use the usual git reference syntax: odoo-test-helper @ git+https://github.com/OCA/odoo-test-helper@master
I think @simahawk was going to setup an release process for odoo-test-helper.

Yeah, I still have to get back to it :sweat: 

Meanwhile, IMO it's better if you use the tarball instead:

`odoo-test-helper @ https://github.com/OCA/odoo-test-helper/archive/refs/heads/master.tar.gz`

2021-12-17 08:02 UTC, JoanMForgeFlow commented
> > @sbidoul When github installs the dependencies, it installs the library: odoo-test-helper-1.1.0, but I think it is out of date, how could I specify in the test-requirements.txt file, the latest version of the OCA repository: https://github.com/OCA/odoo-test-helper.
> 
> You can use the usual git reference syntax: `odoo-test-helper @ git+https://github.com/OCA/odoo-test-helper@master` I think @simahawk was going to setup an release process for odoo-test-helper.
> 
> > Another question, from where does CI downloads the dependencies
> 
> The short answer is: from PyPI.org. A longest answer is it comes from an OCA-hosted index that redirects to PyPI but filters out non-oca Odoo addons, to make sure we test only with OCA dependencies. The [default index is defined in the oca/oca-ci image](https://github.com/OCA/oca-ci/blob/c24a51d3f09c81bfdfa737de9ed16f70ef0a0d7d/Dockerfile#L146-L148).
> 
> > written in the test-requirements.txt file.
> 
> This applies to all python dependencies (found in manifest external_dependencies, for instance), not only those defined in test-requirements.txt

@sbidoul @simahawk thanks for the quick answer and explanation!. :+1:

2021-12-17 08:26 UTC, JoanMForgeFlow commented
@pedrobaeza @sbidoul @simahawk @AaronHForgeFlow @HaraldPanten 

When I run the test I get the following error log. In version 15 model Registry doesn't have 'model_cache' field, and odoo_test_helper is outdated because uses this model. How could we solve this? Thanks in advance

 ```
2021-12-17 08:06:22,023 341 ERROR odoo unittest.suite: ERROR: tearDownClass (odoo.addons.date_range.tests.test_date_range_search_mixin.TestDateRangeearchMixin)
Traceback (most recent call last):
  File "/__w/server-ux/server-ux/setup/date_range/odoo/addons/date_range/tests/test_date_range_search_mixin.py", line 40, in tearDownClass
    cls.loader.restore_registry()
  File "/opt/odoo-venv/lib/python3.8/site-packages/odoo_test_helper/fake_model_loader.py", line 163, in restore_registry
    self.env.registry.model_cache.clear()
AttributeError: 'Registry' object has no attribute 'model_cache'
```

2021-12-17 08:35 UTC, HaraldPanten commented
Hi Joan, this question is out of my knowledge. Probably Stéphane or Simone could advise you

2021-12-17 08:38 UTC, pedrobaeza commented
Probably `odoo-test-helper` should be updated for supporting v15 cc @simahawk

2021-12-17 08:41 UTC, simahawk commented
Here it comes https://github.com/OCA/odoo-test-helper/pull/18

[2.0.0](https://pypi.org/project/odoo-test-helper/2.0.0/) is already available. 2.0.1 will come as the build gets green :wink:

2021-12-17 09:37 UTC, simahawk commented
voilá https://pypi.org/project/odoo-test-helper/2.0.1/

2021-12-17 11:17 UTC, JoanMForgeFlow commented
> voilá https://pypi.org/project/odoo-test-helper/2.0.1/

Thank you so much :)

2021-12-17 11:23 UTC, HaraldPanten commented
@pedrobaeza GO? 👍

2021-12-17 13:21 UTC, pedrobaeza approved these changes

2021-12-17 13:21 UTC, pedrobaeza commented
/ocabot merge nobump

2021-12-17 13:26 UTC, merged