[ADD] remember_tree_column_width: Remember the tree columns' widths across sessions.
OCA/server-ux pull request #524
Opened 2022-08-12 20:41 UTC by frahikLV

2022-08-12 20:41 UTC, frahikLV commented
@luisg123v Review this PR

2022-08-13 21:42 UTC, luisg123v requested changes

2022-08-13 21:42 UTC, luisg123v commented on remember_tree_column_width/readme/ROADMAP.rst
> +* None
This is an optional file. If there's nothing to say, we may remove it

2022-08-13 21:42 UTC, luisg123v commented on remember_tree_column_width/__manifest__.py
> +        "frahikLV",
Could you add myself, too, please?

2022-08-13 21:42 UTC, luisg123v commented on remember_tree_column_width/__manifest__.py
> +            "remember_tree_column_width/static/src/scss/style.scss",
maybe `main.scss`?

2022-08-13 21:44 UTC, luisg123v commented
Hi @carmenmiranda, @hugho-ad 

Could you review, please?

CC @desdelinux

2022-08-15 15:35 UTC, frahikLV commented
@luisg123v Review

2022-08-15 16:18 UTC, CarmenMiranda approved these changes
Technically LGTM 👍🏼 

I would only recommend a little more description in the commit and description of the PR.

2022-08-15 16:24 UTC, pedrobaeza commented
My concern is about the module name. A more standard `web_tree_column_width_remember` name would be advisable, as well as moving it to OCA/web

2022-08-15 16:28 UTC, desdelinux approved these changes
Functional Review is ok

Please, add a description to the PR

2022-08-15 19:14 UTC, luisg123v requested changes
LGTM, but I agree with @pedrobaeza, @CarmenMiranda and @desdelinux:

- Missing description
- Rename as suggested and move to OCA/web

2022-08-17 18:38 UTC, closed without merging