14.0 imp sequence check digit add ean
OCA/server-ux pull request #582
Opened 2023-01-19 12:41 UTC by wouitmil

2023-01-20 08:07 UTC, simahawk requested changes
Can you please amend your commit msg on the next push?
Something like `sequence_check_digit: support ean` or smth similar will work ;)
You can add `[IMP] in front of it if you like.
Guidelines here https://github.com/OCA/odoo-community.org/blob/master/website/Contribution/CONTRIBUTING.rst#commit-message

2023-01-20 08:07 UTC, simahawk commented on sequence_check_digit/__manifest__.py
> +    "version": "14.0.1.1.0",
don't change the version nr, it will get bumped by the ocabot ;)

2025-08-12 08:02 UTC, gurneyalex approved these changes

2025-08-12 08:03 UTC, gurneyalex commented
ocabot merge minor

2026-01-25 12:30 UTC, closed without merging