[FIX] Remove unneeded external_dependencies odoo_test_helper
OCA/server-ux pull request #604
Opened 2023-02-23 15:46 UTC by rven

The python package odoo_test_helper is only needed on the CI environments.

2023-02-23 15:50 UTC, rven commented
Shouldn't the python package odoo_test_helper being installed by the CI?

2023-02-23 16:00 UTC, lmignon requested changes
@rven  You must add the dependency into a test-requirements.txt file to be installed by the CI

2023-02-23 16:08 UTC, etobella commented
The right way, would be your changes and adding it to test-requirements.txt file

2023-02-27 16:08 UTC, lmignon approved these changes

2023-02-27 16:09 UTC, lmignon commented
/ocabot merge patch

2023-04-25 06:47 UTC, closed without merging