[16.0] [MIG] base_export_manager: Migration to 16.0
OCA/server-ux pull request #649
Opened 2023-04-25 04:33 UTC by rjpathan

2023-04-25 21:40 UTC, kikopeiro commented
Here's what I tried:

- I changed the configuration (Accesses Rights) for the res.partner.category  (all accesses)
- I still can access the export option over this model
- Tested with not admin user

Did I miss something? V15 is working fine

What is reproduced is similar to what was discussed in this issue https://github.com/OCA/server-ux/issues/474.

2023-06-07 08:39 UTC, rjpathan commented
@kikopeiro sorry for late reply.

Export action button is disabled with a javascript function https://github.com/rjpathan/server-ux/blob/16.0-mig-base_export_manager/base_export_manager/static/src/js/base_export_manager.js
It seems this is not working in v16.

Sorry, I am not sure how to fix this as I don't have proficiency with the javascript.

2023-06-08 13:54 UTC, hugosantosred commented
@rjpathan I've opened a PR with the fix. In v16 the ListController is defined in OWL, so is needed to patch that controller in order to set the isExportEnable property

2023-06-09 10:33 UTC, rjpathan commented
@hugosantosred Thanks for the fix.

2023-06-23 07:36 UTC, stefan-tecnativa commented on base_export_manager/models/ir_exports_line.py
> +                self.env.invalidate_all()
Passing `flush=True` parameter to invalidate_all() wouldn't be the same as both lines that you wrote?
https://github.com/odoo/odoo/blob/16.0/odoo/api.py#L714-L723

2023-06-26 09:33 UTC, stefan-tecnativa commented
You're pre-commit problem is related with the list_controller.js file. Two possible solutions could be:
1- Convert your code to ESM module (ECMAScript Modules)
2- Use requires to import objects from other files: https://github.com/OCA/OCB/blob/15.0/addons/account/static/src/js/account_payment_field.js#L5

Good Luck!

2023-06-26 15:51 UTC, kikopeiro approved these changes
:+1:  LGTM (without code review)

2023-08-03 05:48 UTC, stefan-tecnativa requested changes

2023-08-03 05:48 UTC, stefan-tecnativa commented on base_export_manager/models/ir_exports_line.py
> +                self.env.invalidate_all()
```
self.browse(one.ids).invalidate_recordset()
one._check_name()
```

2023-08-04 07:04 UTC, pedrobaeza commented
Superseded by #702

2023-08-04 07:04 UTC, closed without merging