[16.0][MIG] base_tier_validation_correction
OCA/server-ux pull request #674
Opened 2023-06-22 14:26 UTC by ChrisOForgeFlow

@ForgeFlow

2023-06-23 19:19 UTC, bosd approved these changes
Code review LGTM :+1:

2023-08-22 08:42 UTC, mariadforgeflow approved these changes
LGTM!

2023-11-29 19:30 UTC, bosd requested changes
Very quick code review.
Please force push to recreate runboat and tests.

2023-11-29 19:30 UTC, bosd commented on base_tier_validation_correction/tests/test_tier_validation.py
> +        doc_user1._invalidate_cache()
```suggestion
        doc_user1.invalidate_recordset()
```
invalidate_cache() is deprecated.
Please change this here, among with the other places it occurs in this file

2023-11-29 19:30 UTC, bosd commented on base_tier_validation_correction/tests/test_tier_validation.py
> +        # Make reversion, now user 1 can reivew
```suggestion
        # Make reversion, now user 1 can review
```

2024-02-14 06:26 UTC, bosd commented
@ChrisOForgeFlow Can you attend to this? 🙏

2025-03-14 16:15 UTC, AlexPForgeFlow commented
Can we reopen and try to get it merged?

2025-03-18 20:02 UTC, bosd commented
@ForgeFlow Can you attend to my comments?

2025-03-19 08:38 UTC, AlexPForgeFlow commented
Hi @bosd !
Applied your comments. Can we merge it?

2025-03-19 15:59 UTC, bosd approved these changes
LGTM Let's Merge!! :confetti_ball:

2025-03-25 09:23 UTC, AlexPForgeFlow commented
@bosd can we merge it?

2025-03-25 10:46 UTC, bosd commented
Yes @AlexPForgeFlow Let's go!

2025-03-25 12:11 UTC, LoisRForgeFlow commented
/ocabot migration base_tier_validation_correction

/ocabot merge nobump

2025-03-25 12:19 UTC, merged