[16.0][FIX] base_substate: track template on substate
OCA/server-ux pull request #736
Opened 2023-10-24 06:28 UTC by Saran440

This PR cherry-pick from https://github.com/OCA/server-ux/pull/735

2023-10-24 09:02 UTC, bosd approved these changes
Code review, LGTM :+1

2023-10-24 09:18 UTC, Dranyel-Bosd approved these changes
Code review, LGTM :+1

2023-11-02 09:00 UTC, bosd commented
@pedrobaeza Can you please merge this? 🙏

2023-11-02 09:17 UTC, pedrobaeza requested changes
Why changing this to make it less performant? I don't like too much to include things that are always evaluated for all the models. This should be solved in other way.

2023-11-02 13:07 UTC, bosd commented
@etobella We are talking about this one. It is not likely to get merged soon in this current form.
Should this block the other pr?

:innocent: Why is this change negativly impacting performant?

2023-11-02 13:17 UTC, pedrobaeza commented
It impacts because this is evaluated for each during in every model in Odoo inheriting from mail thread, instead of only those inheriting from the substate mixin.

2023-11-02 13:28 UTC, etobella commented on base_substate/models/mail_thread.py
> +    _inherit = "mail.thread"
The option would be to add a new abstract like
```python
_name = "base.substate.thread.mixin"
_inherit = ["mail.thread", "base.substate.mixin"]
```

2023-11-03 02:18 UTC, Saran440 commented
Ok, I agree with @pedrobaeza it shouldn't inherit in `mail.thread`

@etobella Thank you for your suggest.
If we use `base.substate.mixin` inherit `mail.thread`
and move function `_track_template()` back to `base.substate.mixin`
it will not create new abstract. what do you think?

```
_name = "base.substate.mixin"
_inherit = "mail.thread"
```

2023-12-12 07:10 UTC, bosd commented
Oops, the discussion here seems to have halted.
As well as the dev/merging of other substate modules.

@Saran440  Can we get things moving again?
Can you rebase/force push to recreate runboat / tests?

2024-01-18 11:42 UTC, bosd commented
Ping @Saran440  It has been a while since we worked on several substate modules.
Things got stale over time. What do we need to do to get things moving again?

2024-01-26 09:44 UTC, Saran440 commented
@bosd I fixed test script and some bug in function `_track_template()`.
Can you check and test template in https://github.com/OCA/account-invoicing/pull/1568 please. Thank you.

2024-02-23 20:06 UTC, bosd commented
> Can you check and test template in [OCA/account-invoicing#1568](https://github.com/OCA/account-invoicing/pull/1568) please. Thank you.

Sorry to keep you waiting...
With the version of `base_substate` in this PR I'm getting an error:

```
RPC_ERROR
Odoo Server Error
Traceback (most recent call last):
  File "/opt/odoo/custom/src/odoo/odoo/http.py", line 1584, in _serve_db
    return service_model.retrying(self._serve_ir_http, self.env)
  File "/opt/odoo/custom/src/odoo/odoo/service/model.py", line 133, in retrying
    result = func()
  File "/opt/odoo/custom/src/odoo/odoo/http.py", line 1611, in _serve_ir_http
    response = self.dispatcher.dispatch(rule.endpoint, args)
  File "/opt/odoo/custom/src/odoo/odoo/http.py", line 1809, in dispatch
    result = self.request.registry['ir.http']._dispatch(endpoint)
  File "/opt/odoo/custom/src/odoo/odoo/addons/base/models/ir_http.py", line 154, in _dispatch
    result = endpoint(**request.params)
  File "/opt/odoo/custom/src/odoo/odoo/http.py", line 697, in route_wrapper
    result = endpoint(self, *args, **params_ok)
  File "/opt/odoo/auto/addons/web/controllers/dataset.py", line 46, in call_button
    action = self._call_kw(model, method, args, kwargs)
  File "/opt/odoo/auto/addons/web/controllers/dataset.py", line 33, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/opt/odoo/custom/src/odoo/odoo/api.py", line 461, in call_kw
    result = _call_kw_multi(method, model, args, kwargs)
  File "/opt/odoo/custom/src/odoo/odoo/api.py", line 448, in _call_kw_multi
    result = method(recs, *args, **kwargs)
  File "<decorator-gen-69>", line 2, in button_immediate_install
  File "/opt/odoo/custom/src/odoo/odoo/addons/base/models/ir_module.py", line 76, in check_and_log
    return method(self, *args, **kwargs)
  File "/opt/odoo/custom/src/odoo/odoo/addons/base/models/ir_module.py", line 491, in button_immediate_install
    return self._button_immediate_function(type(self).button_install)
  File "/opt/odoo/custom/src/odoo/odoo/addons/base/models/ir_module.py", line 615, in _button_immediate_function
    registry = modules.registry.Registry.new(self._cr.dbname, update_module=True)
  File "<decorator-gen-14>", line 2, in new
  File "/opt/odoo/custom/src/odoo/odoo/tools/func.py", line 87, in locked
    return func(inst, *args, **kwargs)
  File "/opt/odoo/custom/src/odoo/odoo/modules/registry.py", line 90, in new
    odoo.modules.load_modules(registry, force_demo, status, update_module)
  File "/opt/odoo/custom/src/odoo/odoo/modules/loading.py", line 488, in load_modules
    processed_modules += load_marked_modules(cr, graph,
  File "/opt/odoo/custom/src/odoo/odoo/modules/loading.py", line 372, in load_marked_modules
    loaded, processed = load_module_graph(
  File "/opt/odoo/custom/src/odoo/odoo/modules/loading.py", line 207, in load_module_graph
    registry.setup_models(cr)
  File "/opt/odoo/custom/src/odoo/odoo/modules/registry.py", line 285, in setup_models
    model._prepare_setup()
  File "/opt/odoo/custom/src/odoo/odoo/models.py", line 2703, in _prepare_setup
    cls.__bases__ = cls.__base_classes
TypeError: Cannot create a consistent method resolution
order (MRO) for bases BaseModel, base, mail.thread, mail.activity.mixin, sequence.mixin, base.substate.mixin

The above server error caused the following client error:
RPC_ERROR: Odoo Server Error
    at makeErrorFromResponse (http://localhost:16069/web/assets/435-e992299/web.assets_backend.min.js:973:163)
    at XMLHttpRequest.<anonymous> (http://localhost:16069/web/assets/435-e992299/web.assets_backend.min.js:981:13)
```

2024-05-30 08:11 UTC, bosd commented
@Saran440 Can you attend to the error? It might be applicable to the backport in V15

2024-11-15 06:28 UTC, bosd commented
What is the status of this one?

2025-03-18 06:27 UTC, bosd commented
@pedrobaeza Is this one ok for you now?

2025-03-18 08:01 UTC, pedrobaeza commented
Why previous approach didn't work?

2025-03-18 09:06 UTC, StefanRijnhart commented
@pedrobaeza See https://github.com/OCA/sale-workflow/pull/3483 for why the previous approach did not always work, and how it can be solved without overriding `write`.

2025-03-18 09:44 UTC, pedrobaeza approved these changes
OK then

/ocabot merge patch

2025-03-18 09:48 UTC, merged

2025-03-18 11:03 UTC, StefanRijnhart commented
@pedrobaeza I take it that you didn't like the solution that depends on the inheritance order?

2025-03-18 11:10 UTC, pedrobaeza commented
Well, I didn't see that alternative approach. I just saw that overwriting the `write` one was too much intrusive, and that they have proposed an alternative one having enough support.

2025-03-18 11:12 UTC, StefanRijnhart commented
@pedrobaeza Well, as you can see in https://github.com/OCA/sale-workflow/pull/3483/files it does not have the intrusive write, and is more in line with the standard Odoo tracking mechanism using the cursor commit hooks. Should we go that way for 17.0?

2025-03-18 11:13 UTC, pedrobaeza commented
OK then, let's improve it in 17.0