[16.0][FIX] base_archive_security:  Confirming quotation issue - portal user
OCA/server-ux pull request #792
Opened 2024-01-02 09:58 UTC by RaoufJabriCamptocamp

This error disappeared with the uninstallation of the module base_archive_security.

FIX : add condition to toggle_active method to check if user is public user or not.

2024-01-02 16:17 UTC, ivantodorovich requested changes
Could you change the commit message to something that makes more sense in this context?

ie:

```
[FIX] base_archive_security: skip check on empty recordset

Also, allow to bypass through a special context key
```

2024-01-02 16:17 UTC, ivantodorovich commented on base_archive_security/models/base.py
> +        # check if user is public user or not.
```suggestion
```

2024-01-02 17:45 UTC, RaoufJabriCamptocamp commented
@ivantodorovich Done

2024-01-02 17:59 UTC, ivantodorovich approved these changes

2024-01-03 11:40 UTC, ivantodorovich approved these changes
Thanks @RaoufJabriCamptocamp !

/ocabot merge patch

2024-01-03 11:44 UTC, merged