[15.0][ENH] base_tier_validation, add Notify Reviewers by Approve Sequence
OCA/server-ux pull request #854
Opened 2024-04-11 10:32 UTC by kittiu

2024-04-11 10:49 UTC, kittiu commented
cc @ps-tubtim

2024-04-29 02:58 UTC, ps-tubtim approved these changes
Functional Test: Ok

2024-08-05 08:56 UTC, Saran440 approved these changes
Tested :+1: . Run on production

2024-08-28 09:47 UTC, bosd commented
On first sight, this looks like an alternative implementation of https://github.com/OCA/server-ux/pull/638 `base_tier_validation_waiting`?

The use case you describe is available in V17. So maybe backport?

2024-12-18 09:42 UTC, Saran440 commented
@bosd Hi, Thank you for suggest.

I tested on v17. it working :+1: but i test on your pr https://github.com/OCA/server-ux/pull/638 but still send email duplicate.

I think I can't backport from v17 to v15 because structure code `base_tier_validation` has changed.

However, this PR shouldn't merged to v15

2024-12-18 09:43 UTC, Saran440 requested changes
In version17 use field name `notify_on_pending` can't merge this PR

2025-05-25 12:24 UTC, closed without merging