[IMP] configurable domain for readonly fields in validation
OCA/server-ux pull request #888
Opened 2024-05-23 17:09 UTC by Kev-Roche

As discussed here : https://github.com/OCA/server-ux/pull/860
This PR make the domain easily editable for readonly fields in validation.

2024-05-23 20:09 UTC, hbrunn requested changes
I was thinking more in the lines of: Extract the body of every for loop in `get_view` into its own function, so programmers can modify each aspect more easily.

But that's probably indeed better done in the v17 version, and also there what you propose seems useful to me. So for me, just renaming the function would make this good to merge.

2024-05-23 20:09 UTC, hbrunn commented on base_tier_validation/models/tier_validation.py
> +    def _get_readonly_domain(self):
this one is very likely to clash with some model function of the same name. I'd suggest something like `_get_tier_validation_readonly_domain` or similar. And for new functions, I think a docstring is always good.

2024-05-24 14:58 UTC, Kev-Roche commented on base_tier_validation/models/tier_validation.py
> +    def _get_readonly_domain(self):
Good point, I changed it.

2024-05-24 17:48 UTC, hbrunn approved these changes

2024-06-19 10:40 UTC, Abranes approved these changes

2024-06-19 12:42 UTC, hbrunn commented
/ocabot merge patch

2024-06-19 12:47 UTC, merged