[FIX] base_tier_validation: Field merge in view
OCA/server-ux pull request #923
Opened 2024-07-16 14:42 UTC by jaenbox

Cherry-pick from 16.0 PR #846

@houzefa-abba

2024-07-17 05:57 UTC, bosd requested changes
LGTM,
Minor comments.
In the logs there is a warning message.
Is introduced by this pr?

```

2024-07-16 14:44:05,047 249 WARNING odoo odoo.addons.base.models.ir_model: Two fields (model_name, model_id) of tier.validation.exception() have the same label: Model. [Modules: base_tier_validation and base_tier_validation] 

```

2024-07-17 05:57 UTC, bosd commented on base_tier_validation/readme/CONTRIBUTORS.rst
The contributors list has been moved to `CONTRIBUTORS.md` please apply the changes there.

2024-07-17 07:04 UTC, jaenbox commented
> Minor comments.
> In the logs there is a warning message.
> Is introduced by this pr?

The warning is not produced by this PR

2024-07-17 08:04 UTC, houzefa-abba approved these changes
Thanks for migrating to 17 :)

LGTM (code review only) aside from the CONTRIBUTORS file that has to be moved

2024-07-23 13:05 UTC, LoisRForgeFlow commented
@jaenbox can you attend the issue with the contributors file?

2024-07-29 07:00 UTC, closed without merging

2024-07-30 08:22 UTC, jaenbox commented
Sorry, I don't know why I closed the PR after making changes to the CONTRIBUTORS.md. I have created a new one #932 with the cherry-pick and the changes in the CONTRIBUTORS.md. Sorry for the inconvenience.

@LoisRForgeFlow 
@houzefa-abba