[17.0][FW] base_tier_validation: multiple ports from 14.0
OCA/server-ux pull request #968
Opened 2024-11-08 12:24 UTC by henrybackman

Port of the following PRs from 14.0 to 17.0:
- https://github.com/OCA/server-ux/pull/421
- https://github.com/OCA/server-ux/pull/412
- https://github.com/OCA/server-ux/pull/426
- https://github.com/OCA/server-ux/pull/451
- https://github.com/OCA/server-ux/pull/583
- https://github.com/OCA/server-ux/pull/630
- https://github.com/OCA/server-ux/pull/682
- https://github.com/OCA/server-ux/pull/873
- https://github.com/OCA/server-ux/pull/960

2024-11-11 10:37 UTC, simahawk approved these changes
LGTM, code review only.

2024-11-11 12:37 UTC, StefanRijnhart commented
#426 and #630 were already ported to 16 in #637 are already present in 17 as such.

2024-11-20 15:03 UTC, TDu commented on base_tier_validation/models/tier_definition.py
> +                ("status", "=", "waiting"),
should not this be 
```
("status", "in", ("waiting", "pending",))
```
The waiting status was added and it is not replacing the pending status

2024-11-22 14:21 UTC, TDu approved these changes

2024-11-25 11:08 UTC, StefanRijnhart commented
@henrybackman thanks for the thumbs up on my comment, but are you going to remove the commits from your branch?

2024-11-25 11:49 UTC, LoisRForgeFlow requested changes
Just blocking the merge while https://github.com/OCA/server-ux/pull/968#issuecomment-2468080707 conversation is resolved

2024-11-25 15:14 UTC, henrybackman commented
> @henrybackman thanks for the thumbs up on my comment, but are you going to remove the commits from your branch?

@StefanRijnhart Thank you for reminding me, honestly thought I had already removed them, my bad. They have been removed now.
FYI @LoisRForgeFlow

2024-11-25 16:46 UTC, LoisRForgeFlow commented
@StefanRijnhart good from your side now?

2024-11-26 12:09 UTC, StefanRijnhart approved these changes
Thanks!

2024-11-26 15:08 UTC, LoisRForgeFlow approved these changes
/ocabot merge minor

2024-11-26 15:14 UTC, merged